[pytest]
addopts = --cov=. --cov-report=xml:coverage.xml --cov-report=term-missing
testpaths = tests

[coverage:run]
omit =
    */main.py
    tests/*
    .venv/*

[coverage:report]
omit =
    */main.py
    tests/*
    .venv/*
