# Cambia el projectKey al formato: Nombre_Apellido_t8
sonar.projectKey=Carlos_Oriundo_t1

sonar.sources=.

sonar.exclusions=.venv/**,tests/**,**/__pycache__/**,*.pyc

sonar.host.url=https://sonarqube.ingsoftware.lat/

# Reemplaza con tu token personal de SonarQube
sonar.token=sqp_2459d4c4c7138483baf34d08154e1762ae2e125d

sonar.tests=.
sonar.test.inclusions=**/tests/**,**test_*.py
sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.12
sonar.scm.disabled=true
